import type {Metadata} from 'next';
import React from 'react';
import {DM_Sans} from 'next/font/google';
import './globals.css';

const inter = DM_Sans({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="ru">
			<body className={inter.className}>
				{children}
			</body>
		</html>
	);
}